people:
  - name: gardener
    avatar: https://avatars.githubusercontent.com/u/11409143?v=4
    candle: gardener
    color: '#ff0000'
  - name: Filipko
    avatar: https://avatars.githubusercontent.com/u/15289967?v=4
    candle: fs
    color: 'transparent'
  - name: Marcel
    avatar: https://avatars.githubusercontent.com/u/18122517?v=4
    candle: marcel
    color: '#0000BA'
  - name: Kristina
    avatar: /static/kristina.jpg
    candle: kristina
    color: '#00ffff'
  - name: Emmika
    avatar: /static/emmika.jpg
    candle: emmika
    color: '#f42069'
  - name: MisQo
    avatar: /static/misqo.jpeg
    candle: misqof
    color: '#ff00ff'
  - name: Janči
    avatar: https://media.ksp.sk/cache/fe/f7/fef7dd1860d8944e1a1369bdf7c08832.jpg
    candle: plachy-verejny-23z
    color: '#04A4F9'
  - name: Dušan
    avatar: https://ca.slack-edge.com/T314M4THC-U0488771Z6W-441dde898200-512
    candle: dusan
    color: '#2714D2'
  - name: Adri
    avatar: https://cdn.discordapp.com/avatars/643874860426199066/6d1bb9bdaea1f869d7069dfac2fa76e0.png
    candle: brosk
    color: '#EA9045'
  - name: Stanko
    avatar: https://ca.slack-edge.com/T314M4THC-U04605F9ZS6-91e48a11d936-192
    candle: stanko
    color: '#14044D'
